### ISSUE TITLE
Hashing

### ISSUE THREAD

**Issue by dozykeys** [ipfs/ipfs-docs#1259]
When i try to upload to ipfs, everything is successful, but whenever i try to use blake2b for the hashAlg,it fails with error, no hasher found for blake2b-208. I observed that just sha256 and sha512 are available.

IPFS Version : 0.63.5
Below is the full error

[nodemon] restarting due to changes...
[nodemon] starting `node dozie2.js`
Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/12D3KooWRnb6NYEcUaeciXQhCaERJnqcnbPGuQ9BZhQgjqqM64Lx
Swarm listening on /ip4/192.168.8.96/tcp/4002/p2p/12D3KooWRnb6NYEcUaeciXQhCaERJnqcnbPGuQ9BZhQgjqqM64Lx
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/12D3KooWRnb6NYEcUaeciXQhCaERJnqcnbPGuQ9BZhQgjqqM64Lx
file:///Users/macbook/Documents/node_apps/RC3-NFT/node_modules/ipfs-core-utils/src/multihashes.js:10
const LOAD_HASHER = (codeOrName) => Promise.reject(new Error(`No hasher found for "${codeOrName}"`))                                               
``` 
Error: No hasher found for "blake2b-208"
    at Multihashes.LOAD_HASHER [as _loadHasher] (file:///Users/macbook/Documents/node_apps/RC3-NFT/node_modules/ipfs-core-utils/src/multihashes.js:10:52)
    at Multihashes.getHasher (file:///Users/macbook/Documents/node_apps/RC3-NFT/node_modules/ipfs-core-utils/src/multihashes.js:70:31)
    at addAll (file:///Users/macbook/Documents/node_apps/RC3-NFT/node_modules/ipfs-core/src/components/add-all/index.js:97:30)
    at addAll.next (<anonymous>)
    at file:///Users/macbook/Documents/node_apps/RC3-NFT/node_modules/ipfs-core-utils/src/with-timeout-option.js:64:60
    at AsyncGenerator.next (<anonymous>)
    at last (/Users/macbook/Documents/node_apps/RC3-NFT/node_modules/it-last/index.js:13:20)
    at IPFS.add (file:///Users/macbook/Documents/node_apps/RC3-NFT/node_modules/ipfs-core/src/components/add.js:14:26)
    at /Users/macbook/Documents/node_apps/RC3-NFT/dozie2.js:64:23```

**Comment by johnnymatthews** [comment]
Looks like this got missed along the way. Sorry about that. In future, please use https://discuss.ipfs.tech/ if you just need general support.
